### PR TITLE
Add flag similarity between Liechtenstein and Haiti

### PR DESCRIPTION
**Pull request by x51mon**
The flags only differ in the symbol/coat of arms and its position.

Languages other than German are auto translated.

### CODE REVIEW

**Comment by axelboc** [comment]
@aplaice per https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#flag-similarity-field, I'm not convinced this pair of flags qualifies for having flag similarity information. Haiti has a _coat of arms_ of sorts in the middle, and Liechtenstein has a _symbol_ in the top left corner. Therefore, they are more different than our guidelines allow.

That being said, the ΔE of the two blues is 26.7, which qualifies as a negligible difference. So if we want to add this flag similarity pair, we could add a new critical difference to our guidelines as follows:

- decorations of different types in different positions (e.g. coat of arms in middle, symbol in top left corner)

**Comment by aplaice** [comment]
@axelboc You're right!

My "reactions" were intended to indicate that this is an interesting case that's worth considering, but that I hadn't yet really thought about it or looked at the commit. (It's probably far from clear...)

FWIW I've never confused these two particular flags (and I confuse many of our flags! :)), so from my perspective our criteria do correctly identify "confusingness".

@x51mon if you're comfortable answering (and please feel free to say no), is this pair of flags a set that you've mixed up/you know somebody who mixes them up, or is it just a pair that you think "should" be on the flag similarity set?

(The similarity between Liechtenstein and Haiti _is_ IMO a good mnemonic for the Country→Flag cards, but (cf. #132) that isn't the purpose of the "Flag similarity" field.)

Hence, overall, I'd lean against changing the criteria.

**Comment by x51mon** [comment]
From what you write I think I might have assumed a different purpose of this field actually. I did not yet go through all the flags but, except for a few cases, I've seen this field more as a mnemonic and/or fun fact field.

So @aplaice to answer your question: no I did not mix them up, I've just noticed that they use the same colours and found it interesting and somehow worth memorizing.

To illustrate this with another example, when going through the cards it seemed to me that Russia, Slovenia and Slovakia use (almost) the same colours but I wasn't completely sure about the order because they don't get shown next to each other. So to me that would be interesting to point out and also put on the card for the simple reason of not having to look it up. But I get now that that's not the point of this field :)

**Comment by axelboc** [comment]
Right, makes sense, it is quite a confusing field! 😄 I'll close this PR then.

**Pull request closed without merging**
