### PR TITLE
Fix outdated capitals in Norwegian

### PR DESCRIPTION
**Pull request by axelboc**
See #416.

### CODE REVIEW

**Comment by aplaice** [comment]
We'd also need to update our [Norwegian contributing guidelines](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#norwegian-bokm%C3%A5l), since there Wikipedia is only a source of third priority. The current Norwegian capitals in the deck are indeed consistent with the first-priority source.

I 100% agree with Bucharest no longer being the capital of Russia. :)

**Comment by aplaice** [comment]
Given that:

1. the [highest priority source](https://www.regjeringen.no/no/dokumenter/statsnavn-hovedsteder-og-nasjonaldager/id87863/) was last updated in 2013, 
2. the [second highest priority source](https://snl.no/) at least sort-of agrees with Wikipedia in all three cases:
    For [Kazakhstan](https://snl.no/Kasakhstan) it has a different spelling (Nursultan in snl vs. Nur-Sultan in Wikipedia), but no mention of Astana.
    For [Sri Lanka](https://snl.no/Sri_Lanka)  it has "Colombo og Sri Jayewardenepura Kotte", which is slightly weird.
    For [Tuvalu](https://snl.no/Tuvalu) it agrees completely.

it might make sense to follow Wikipedia (or SNL?). I'd consult with @Vages first, though.

**Comment by axelboc** [comment]
Yeah good point, let's wait on @Vages' input.

Some of the inconsistencies are caused by the presence of a paren block that gives an alternate name or spelling. I've actually just spotted another one: `Helsingfors (Helsinki)`. In such case, if the source order remains the same, then we could at least apply the rule of moving the alternate name/spelling to the _Capital info_ field, along with additional information (if there isn't already).

That being said, I feel like the first two sources will never be as up to date as Wikipedia. `Nur-Sultan is a good example. I think it wasn't clear at first whether it was going to be spelt with a hyphen or not, but then it got clarified by official Kazakh institutions. So I'd be in favour of putting Wikipedia first and of using the other two sources as back-ups for any missing/unclear information.

To support my argument, I'll quote the current capital info of Kiribati that Vages wrote, which I've translated back into English:

> Many consider Bairiki as the capital of Kiribati (also the Ministry of Foreign Affairs in Norway) because both the parliament and the president once had a seat there. Since the year 2000, the parliament and ministries have been spread across South Tarawa.

This is basically saying that the Ministry of Foreign Affairs in Norway is wrong and that Wikipedia is right... So we should probably make it official. 😄

**Review by aplaice — APPROVED** [review]

**Comment by aplaice** [comment]
> In such case, if the source order remains the same, then we could at least apply the rule of moving the alternate name/spelling to the Capital info field, along with additional information (if there isn't already).

Yeah, that makes sense.

<hr/>

> That being said, I feel like the first two sources will never be as up to date as Wikipedia.

FWIW the SNL article on Kazakhstan was last updated on 14 January 2021, so it's not that old, but indeed it won't ever be as up-to-date as Wikipedia. OTOH capital and country info don't change _that_ often, so frequent updates mostly aren't that essential.

<hr/>

Ugh, I can't explicitly add Vages as a reviewer.

**Comment by axelboc** [comment]
I've added all the users who contributed translations as members of this repo with Read access. Hopefully, this means we'll be able to add them as reviewers (once they've accepted the invitations).

**Comment by Vages** [comment]
Your arguments for prioritizing SNL over the Ministry of foreign affairs are sound. I'll summarize as follows:

- Ministry of foreign affairs may have diplomatic reasons for lagging the _de facto_ changes. Thay also don't seem to update things that often.
- Store norske leksikon (SNL) have professional editors, usually academics without a direct bond to the government. In my opinion the most authorititative source.
- Wikipedia is mostly correct and usually the first source to be updated, and quickly corrected. «Wrong, but not for long»

I'll update the contributing guidelines to reflect this.

**Comment by axelboc** [comment]
Sorry, haven't had time to come back to this. Given @Vages feedback, and our decision to use English Wikipedia as our official source for factual information https://github.com/anki-geo/ultimate-geography/issues/416#issuecomment-821864712, I'm going to close this PR and deal with all the factual inconsistencies at once.

**Pull request closed without merging**
