### PR TITLE
Chinese/ZH Translation

### LINKED ISSUE #493: Add Chinese Version
Hi, how can I contribute to a Simplified Chinese version with ultimate-geography?
Shall I modify the ultimate-geography/src/data/*.csv ? And add a new column for xxx:cn?
And I'll be appreciated if someone can provider me a method to do this.

### PR DESCRIPTION
**Pull request by ruin1990**
Fix #493

An encoding issue occurred when I translate desc.html into Chinese. ([brain-brew#39](https://github.com/ohare93/brain-brew/issues/39))
desc_zh.html review in my repo's branch: [ruin1990/ultimate-geography#translation_zh](https://github.com/ruin1990/ultimate-geography/tree/translation_zh)
I think other commits should be okay for pull

### CODE REVIEW

**Comment by aplaice** [comment]
On first glance, this looks complete (other than `desc_zh.html`)! Thanks very much!

(Unfortunately, I'm incapable of checking the translations themselves.)

**Comment by ruin1990** [comment]
> On first glance, this looks complete (other than `desc_zh.html`)! Thanks very much!
> 
> (Unfortunately, I'm incapable of checking the translations themselves.)

Oh, may i invite someone else to check it?

**Comment by ohare93** [comment]
Agreed, looks good :+1:

**Review by aplaice — APPROVED** [review]
As noted, I'm not really able to judge the contents of the translation — the structure is correct.

I'm not sure if providing the English version of all countries makes sense (e.g. China itself, or nearby countries, for which the English name is much more recent than the Chinese name), but I'll defer to your judgement. (It might make sense for consistency.)

It'd be nice if this were double-checked for typos by a second person fluent in Chinese, since for the other languages we've been able to at least approximately check for whether there weren't some obvious mistakes (due to being able to read the script), but it's not critical.

<hr/>

> 中国的一部分。(少数国家还没有认同)

I'd have preferred if this were phrased more neutrally, but I'm not capable of judging this other than through automatic translation (so I don't feel comfortable fighting over phrasing) and this combination (given Taiwan being present at all) is probably the best that we can agree on, if this deck is to be usable in China. (I now feel like Google or Apple...)

<hr/>

Thanks again! :)

**Comment by ruin1990** [comment]
> I'd have preferred if this were phrased more neutrally, but I'm not capable of judging this other than through automatic translation (so I don't feel comfortable fighting over phrasing) and this combination (given Taiwan being present at all) is probably the best that we can agree on, if this deck is to be usable in China. (I now feel like Google or Apple...)

是的，这个我和一些朋友讨论过，中国人如果看到有关台湾的言论都会比较激动，我因此采用了更容易被中国人接受的表述

**Comment by ohare93** [comment]
If we're going to start indirectly translating the deck in order to suit the sensibilities of the recipients (which feels very wrong to me) I would prefer saying nothing in the Country Info for Taiwan for the Chinese version. Not the current info "Partially recognised state claimed by China" or @ruin1990's translation "Part of China. (A few countries have not yet agreed)", just blank.

**Comment by ohare93** [comment]
> Chinese people will be more angry if they see remarks about the division of Chinese territories

My own personal opinion of Taiwan's autonomy aside, I don't see how the statement "Partially recognised state claimed by China" could bring up angry remarks. It is partially recognised. It is claimed by China. Nothing there says "Not a part of China, but China thinks so".

There are other such territories in the world (and thus in the deck) which one or more states claim. We should talk about it without giving one or the other more weight, and that is what I believe we already do. We state only indisputable facts in a neutral manner "Partially recognised"/"Independent state" and "Claimed by ...".

@ruin1990 you are stating that Chinese people studying this deck would be angry that the deck is not taking the side of China (that Taiwan is a part of China). **But the deck does not take any side.** It is a list of facts. In the world of Geography facts are really just "what everyone agrees", especially when it comes to a countries autonomy/independence. _It is not a fact that Taiwan is a part of China; just as it is not a fact that it is an independent state._ **It is disputed.** Thus the deck reflects that, and should continue to do so, regardless of the language.

**Comment by ohare93** [comment]
Regardless, thanks again for your efforts of translating the deck thus far :+1:

**Comment by ruin1990** [comment]
In addition, perhaps the following translation is more in line with Wikipedia's statement
中国宣称对台湾拥有主权，但仅被部分国家承认

In fact, these two translations have similar meanings in Chinese, but I did bring my own emotional touch when translating, because I am also worried that this Note will affect some people to boycott this deck.

Maybe we can choose not to generate China Notes  and Taiwan Notes when built with brain-brew to circumvent this problem. After all, these two geographic information are familiar to Chinese people.

**Comment by aplaice** [comment]
> 中国宣称对台湾拥有主权，但仅被部分国家承认

Thanks, that's much better IMO!

<hr/>

> Maybe we can choose not to generate China Notes and Taiwan Notes when built with brain-brew to circumvent this problem.

That'd be unfortunate, but it might end up being a solution.

**Comment by ruin1990** [comment]
> > 中国宣称对台湾拥有主权，但仅被部分国家承认
> 
> Thanks, that's much better IMO!
> 
> > Maybe we can choose not to generate China Notes and Taiwan Notes when built with brain-brew to circumvent this problem.
> 
> That'd be unfortunate, but it might end up being a solution.

**Comment by ruin1990** [comment]
Emmm... I think the desc_zh.html maybe okay to commit now.

**Comment by ruin1990** [comment]
Oh, how can I pull again?

**Comment by aplaice** [comment]
> I modified it and recommitted

Thanks!

<hr/>

>  May I add some translator notes in desc_zh.html? To explain that some disputes between China and Taiwan notes can be avoided by deleting the Notes directly.

If you think that it's likely to help, then yes.

**Comment by ruin1990** [comment]
> If you think that it's likely to help, then yes.
Okay, I commit the desc.html now.
And if someone have issues with this,  [Translate deck header guide (EN&CN)](https://github.com/anki-geo/ultimate-geography/discussions/503) may helps that

**Comment by aplaice** [comment]
@axelboc Do you have any general comments to add?  I'll wait until next week and then merge.  (No pressure — we can amend things later if you have any suggestions (or not, if you don't have any :))!)


<hr/>

I'd also be most comfortable if somebody from Taiwan could weigh in on the translation (other than on choice of character set — Simplified definitely makes sense IMO) — I don't want to offend anybody with the deck, but I also don't want us to be taking any sides.  (To the extent that I can tell, everything is OK now, but it's obviously very hard for me to tell.)  This is obviously in now way a blocker — as mentioned above, I'm mainly waiting in case @axelboc wants to say something (he's the main maintainer and more-or-less the creator of the deck in its current form).

**Comment by axelboc** [comment]
Thanks for the ping @aplaice, and for your activity on the repo during the holidays! I haven't been active myself as I recently bought a new place and have been moving, unpacking and DIYing away! 🎉 I'll take a look at this PR this week/week-end hopefully. (Thanks @ruin1990 for your contribution!)

**Comment by aplaice** [comment]
> Ask and ye shall receive. I sent this along to my few Taiwanese friends.

Thanks very much!

<hr/>

> I am definitely opposed to having a link to a "fixed" version listen in the deck description itself. At least in such a blatant way.

Yeah, that should certainly go. (I'm very sorry for letting this through. It's extremely embarrassing — I have no idea how I missed it; after all it's the one part that I can understand without google translate... (I think I copy-pasted the text into translate without the link and then forgot about the link???))

> I also do not appreciate myself or my fellow maintainers being disparaged in this way. As having knowledge based on Wiki and Google. @ruin1990 I have been to Taiwan. Have you?

I had taken the relevant phrasing to mean that we were relying on Wikipedia as the ultimate source of truth (irrespective of what we actually think), though given the mention of Google your interpretation might be more valid.


<hr/>

I'm personally least bothered about the translation note in the Chinese description since it's easily ignored, it was phrased (as far as I could tell...) as directly from the translator, and if it were to make users from mainland China happy, without bothering anybody else, then it'd be a relatively low price.  OTOH if it's making people from Taiwan unhappy or angry, as it seems to be, it definitely needs to go!  (Possibly replaced with just a suggestion to remove the offending notes, as discussed originally.)

My greatest concerns are about the main contents of the deck — [the name used for Taiwan itself](https://github.com/anki-geo/ultimate-geography/blob/e565521940a8f34e1e070fe8c6bffbb9252d8cb9/src/data/country.csv#L142):

> 台湾(Taiwan)

[the description of Taiwan](https://github.com/anki-geo/ultimate-geography/blob/e565521940a8f34e1e070fe8c6bffbb9252d8cb9/src/data/country_info.csv#L26):

> 中国宣称对台湾拥有主权，但仅被部分国家承认

and [the name used for Taipei](https://github.com/anki-geo/ultimate-geography/blob/e565521940a8f34e1e070fe8c6bffbb9252d8cb9/src/data/capital.csv#L140)

> 台北(Taipei)

(The names seem to be the source of their English equivalents (e.g. 台湾 = Táiwān AFAICT), but on Chinese Wikipedia there appear to be several different articles for both Taiwan and Taipei and I'm not sure if we're using the correct name.  The description is the revised one, and I think it's OK, but a second (different) native opinion would be useful.)

**Comment by chouchoube** [comment]
Hi! I am from Taiwan. @ohare93 led me here. I made an account to comment.

Generally I think the translation looks very diligent, and it must have taken a lot of effort for @ruin1990. But I think he comes from a different background, as in China they are always taught that Taiwan is a part of China. If they haven't really been to Taiwan then they wouldn't really feel that it was different from China. 

Taiwanese people need a visa to enter mainland China. But so do Chinese people need a visa to enter Taiwan. You cannot just show your passport. In my opinion that makes a very big difference. We are a country, and not a part of China. You do not need a visa to get into part of your country. 

Some people who live in Taiwan came here from China when very young after WW2, and they still feel that China is their home. I would say, most of the people below 40 feel that Taiwan is their home, itself. We have our own values as a nation. We take this place as their home and country. Instead of a communist nation.

> the description of Taiwan:
>
>    中国宣称对台湾拥有主权，但仅被部分国家承认

It seems that he tried to make it not provocative to Taiwanese. This is accurate. But the one before was not.

> The names seem to be the source of their English equivalents (e.g. 台湾 = Táiwān AFAICT),
> and the name used for Taipei
>
>   台北(Taipei)

These both are correct.

**Comment by aplaice** [comment]
Thanks very much @chouchoube for your feedback and for creating an account to comment! If you have any further suggestions (regarding the controversial issues or anything else!), please don't hesitate to write.

<hr/>

I think that the main remaining part\* is changing the translator's note in the description to be less contentious.

@ruin1990, if you would be willing and when you have the time, please amend it (ideally to just say that the user can remove the controversial notes). I understand that this is a difficult topic also for you, and I'm sorry if this is bothering you. I also appreciate that you're contributing to the deck despite your disagreement with the map.

However, I don't think that we (or from what I can tell, Wikipedia) are taking a side, with the map. AFAIU from the point of view of people from Taiwan the fact that the map of China has Taiwan marked at all (even partially) is, just as problematic as the fact that Taiwan is only partially marked is for people from China.

I also don't think that we're misrepresenting the situation — China does have a historical claim on Taiwan, but currently doesn't control it and many countries disagree with its claim.

\* Apart from any comments axelboc might have.

**Comment by axelboc** [comment]
I've just had a look, sorry for the wait! 🙏 

First of all, I have to say that the translation looks very impressive and thorough. I've done a few random checks and could not find anything to pick on. Even the formatting (punctuation, spacing, etc.) looks consistent, so thank you again @ruin1990!

Now, in regards to the translators note in the deck description, my vote goes to removing it completely (as opposed to rewording it). Here is my reasoning:

- A lot of things in political geography are touchy, and Taiwan's sovereignty is far from being the only exception (especially when you start including maritime disputes...) We can't possibly please everyone, which is why we've always stuck with the guideline of leaving it to Wikipedia to resolve disputes. Whether Wikipedia is itself biased is another story, which I don't think is worth arguing over either.
- We're maintaining a geography flashcard deck, not a diplomatic reference. If people are taught something else than what is presented in this deck, then they are free to ignore it, delete the contentious content or stop using the deck altogether.
- Addressing a note about Taiwan to all Chinese-speaking users is, in my opinion, biased in itself, especially considering that a lot of people who speak Chinese are not Chinese (Mandarin is spoken at least in Singapore, Malaysia, Hong Kong, Macau). Perhaps some of these people may find it more offensive if the dispute over Taiwan were to be emphasized in any way in the deck description.

**Comment by ruin1990** [comment]
AFAIK, Taiwan uses Traditional Chinese. This simplified Chinese version may not be suitable for them. I originally planned to translate a traditional Chinese version for them to see, which might avoid some problems. Please understand that the dissemination of similar information in China may even be considered illegal.
In addition, I am from Fujian, and my family is surrounded by many friends who come to work in Taiwan. The translator's note is to allow me to translate this document without violating some laws.
You are right. Maybe I can be more neutral. I will see how to delete it later. We have not paid attention to this issue since we are celebrating the Spring Festival recently.
In addition, I recently discovered a method for translating templates, and I am about to release it and discuss it with you.

**Comment by ruin1990** [comment]
> Now, in regards to the translators note in the deck description, my vote goes to removing it completely (as opposed to rewording it). Here is my reasoning:

@axelboc Can I modify the translator's note like this? I have removed some less neutral remarks, and try my best to let all kinds of readers use this deck seriously. If it still doesn't work, then I will delete this translator's note.

译者注：作为中文使用者，本卡组中可能有一些争议内容会让您觉得不舒服，这个毕竟众口难调。但是除此以外的其他国际地理知识不得不说做的非常的好，我们完全可以取其精华，去其糟粕（比如直接搜中国和台湾的卡片直接删了了事，眼不见为净）。
目前主要争议就是中国版图和台湾的描述与国旗，欢迎大家参考<a href="https://commons.wikimedia.org/wiki/File:China_in_its_region_(claimed_and_disputed_hatched).svg">地图问题</a>和<a href="https://github.com/anki-geo/ultimate-geography/issues/494#issuecomment-996717941">外国友人的建议</a>一起努力让维基上的内容变更(当然这很难)，让世界更了解我们中国。

**Comment by axelboc** [comment]
Thanks for trying, but sorry, this is still far from neutral. Please remove altogether.

**Comment by ruin1990** [comment]
> Thanks for trying, but sorry, this is still far from neutral. Please remove altogether.

Okay, I have deleted the translator's note.

**Comment by josealberto4444** [comment]
Maybe we also want to squash some commits before merging the PR.

**Comment by ohare93** [comment]
> Maybe we also want to squash some commits before merging the PR?

Of course! Squash and merge is the only way 😉

**Comment by josealberto4444** [comment]
Hahaha. I don't know how that button works (I really hate the Github workflow), but maybe we don't want to squash them all into a single commit? Anyway, I say it just as a suggestion, you all decide. ^^

**Comment by axelboc** [comment]
Alright, let's do this!!

**Pull request merged**
