### PR TITLE
Translate deck description to Spanish

### LINKED ISSUE #510: Translating the description to Spanish
Hi,

I've seen in the Chinese translation that the description was also translated. What should I do to translate it to Spanish? It's just about creating `desc_es.html`? (pinging @ohare93 as the Brain-Brew maintainer. ^^)

### PR DESCRIPTION
**Pull request by josealberto4444**
I think I did everything needed and this should close #510. =P

### CODE REVIEW

**Comment by ohare93** [comment]
Looks good to me :+1: did you run it?

**Review by ohare93 — APPROVED** [review]

**Comment by josealberto4444** [comment]
> Looks good to me +1 did you run it?

Nope. How do I do that?

**Comment by ohare93** [comment]
> > Looks good to me +1 did you run it?
> 
> Nope. How do I do that?

I presume you have the repo locally? Just follow: https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#getting-started ask if you need help :+1:

**Comment by josealberto4444** [comment]
> I presume you have the repo locally? Just follow: https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#getting-started ask if you need help +1

Thanks! It worked without problem (I used python 3.9 instead of python 3.7). All languages have the corresponding description. ^^

**Review by axelboc — APPROVED** [review]

**Comment by aplaice** [comment]
I've merged and squashed. (I'm not too happy about GitHub's branch workflow, but I think in this case the result is OK.)

**Pull request merged**
