### PR TITLE
update spelling/usage/grammar

### PR DESCRIPTION
**Pull request by horwitz**

### CODE REVIEW

**Review by aplaice — APPROVED** [review]
This looks great! Thanks!

I'm not sure about the Oxford comma, but we already seem to have it elsewhere, so it's probably worth being consistent about its use.

**Comment by horwitz** [comment]
> This looks great! Thanks!
> 
> I'm not sure about the Oxford comma, but we already seem to have it elsewhere, so it's probably worth being consistent about its use.

My thoughts too—consistency was the motivation for the Oxford-comma updates in this PR.

**Review by axelboc — APPROVED** [review]
So many typos! 😱

**Comment by ohare93** [comment]
Oxford commas are the best :100: :ok_hand:

**Pull request merged**
